export const commandCategories = {
  INFO: [
    {
      name: "ping",
      requiredpermissions: "",
      usage: "/ping",
      example: "/ping",
      description: "Check the bot's latency",
    },
    {
      name: "serverinfo",
      requiredpermissions: "",
      usage: "/serverinfo",
      example: "/serverinfo",
      description: "Get information about the server",
    },
    {
      name: "userinfo",
      requiredpermissions: "",
      usage: "/userinfo <user>",
      example: "/userinfo @JohnDoe",
      description: "Get information about a user",
    },
  ],
  MODERATION: [
    {
      name: "deafen",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Deafen a user",
    },
    {
      name: "kick",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Kick a user from the server",
    },
    {
      name: "lock",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Lock a channel",
    },
    {
      name: "mute",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Mute a user",
    },
    {
      name: "undeafen",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Undeafen a user",
    },
    {
      name: "delwarn",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Delete a specific warning",
    },
    {
      name: "warn",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Warn a user",
    },
    {
      name: "modlogs",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "View moderation logs",
    },
    {
      name: "softban",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Soft ban a user",
    },
    // need to add ban and unban
  ],
  MANAGER: [
    {
      name: "clearwarn",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Clear warnings for a user",
    },
    {
      name: "addRole",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Add a role to a user",
    },
    // delrole
    //nickk
  ],
  ROLES: [
    {
      name: "addrank",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Add a new rank",
    },
    {
      name: "delrank",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Delete a rank",
    },
    {
      name: "ranks",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "List available ranks",
    },
    {
      name: "rank",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Check a user's rank",
    },
    {
      name: "roleInfo",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Get information about a role",
    },
    {
      name: "roles",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "List server roles",
    },
  ],
  UTILS: [
    {
      name: "clean",
      description: "",
      requiredpermissions: "",
      usage: "",
      example: "",
    },
    {
      name: "clear",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Clear messages in a channel",
    },
    {
      name: "delslmode",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Delete slowmode setting",
    },
    {
      name: "remind",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Set a reminder",
    },
    {
      name: "setnick",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Set a user's nickname",
    },
    {
      name: "slowmode",
      requiredpermissions: "",
      usage: "",
      example: "",
      description: "Set slowmode for a channel",
    },
  ],
};
